name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install --immutable
      - name: Run all
        uses: borales/actions-yarn@v5
        with:
          cmd: all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    env:
      USERNAME:
      SPECIAL:
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install --immutable
      - name: Run all
        uses: borales/actions-yarn@v5
        with:
          cmd: all
      - uses: ./
        # with:
        #   allowed-commit-types: "feat,fix" # Optional, set if you want a subset of commit types to be allowed.
